grovesNL/spirv_cross

- .travis.yml
- appveyor.yml
- examples/src/hlsl/main.rs
- spirv_cross/Cargo.toml
- spirv_cross/src/bindings.rs
- spirv_cross/src/hlsl.rs
- spirv_cross/src/lib.rs
- spirv_cross/src/spirv.rs
- spirv_cross/src/wrapper.cpp
- spirv_cross/src/wrapper.hpp
Split `parse` from `HlslCompiler` into `SpirvParser`, remove namespace
> Split compiler into `SpirvParser`

- README.md
- examples/src/hlsl/main.rs
- spirv_cross/src/bindings.rs
- spirv_cross/src/hlsl.rs
- spirv_cross/src/lib.rs
- spirv_cross/src/spirv.rs
- spirv_cross/src/wrapper.cpp
- spirv_cross/src/wrapper.hpp
- This simplifies the FFI C externs by avoiding crossing FFI boundary to call constructors/destructors (instead parse and compile methods are provided).
- Parse now returns the entry points also, instead of keeping the compiler alive for deferred queries. If this turns out to be too expensive then these can be switched back to functions, however most of this information should be relatively cheap and will usually be needed by the caller anyway.
- One (possibly large) downside to this approach is that SPIR-V modules are [parsed twice, although this will hopefully improve in the future](https://github.com/KhronosGroup/SPIRV-Cross/issues/287). However the parsing should be cheap so it may not be an issue at the moment.
> Simplify FFI

- README.md
- examples/src/hlsl/main.rs
- examples/src/msl/main.rs
- spirv_cross/src/bindings.rs
- spirv_cross/src/compiler.rs
- spirv_cross/src/hlsl.rs
- spirv_cross/src/lib.rs
- spirv_cross/src/msl.rs
- spirv_cross/src/spirv.rs
- spirv_cross/src/wrapper.cpp
- spirv_cross/src/wrapper.hpp
* Adapt the API to better fit the C++ API, which should allow to easier extend the library. Current API would require reparsing the module multiple times (e.g set/get decorations).
This mostly reverts the changes from #https://github.com/grovesNL/spirv_cross/pull/4
* Added new `set/get_decoration` functions, which are needed for patching the HLSL output in gfx-rs.
> [RFC] Refactor API and add decoration reflection

- README.md
- examples/src/hlsl/main.rs
- examples/src/msl/main.rs
- spirv_cross/Cargo.toml
- spirv_cross/src/compiler.rs
- spirv_cross/src/hlsl.rs
- spirv_cross/src/msl.rs
- spirv_cross/src/spirv.rs
Testing out the idea in #10 to use generic methods instead.
> Use generic `Ast` methods

- bindings_generator/src/main.rs
- examples/src/hlsl/main.rs
- examples/src/msl/main.rs
- spirv_cross/Cargo.toml
- spirv_cross/src/bindings.rs
- spirv_cross/src/compiler.rs
- spirv_cross/src/hlsl.rs
- spirv_cross/src/msl.rs
- spirv_cross/src/spirv.rs
- spirv_cross/src/wrapper.cpp
- spirv_cross/src/wrapper.hpp
- spirv_cross/tests/hlsl_tests.rs
- spirv_cross/tests/msl_tests.rs
- spirv_cross/tests/spirv_tests.rs
Builds onto #24 to replace `ParserOptions` with methods. This may also fix the CI failures if memory was being freed too early.
> Refactor #24

- spirv_cross/src/bindings.rs
- spirv_cross/src/compiler.rs
- spirv_cross/src/spirv.rs
- spirv_cross/src/wrapper.cpp
- spirv_cross/src/wrapper.hpp
Particulary tailored towards the needs of gfx-rs. Constant references in spirv-cross are stored a bit awkwardly due to unions and wrapping inside matrix structs, which complicates the API for us, but we only need the scalar constants.
> Add API for changing specialization constants

- spirv_cross/Cargo.toml
- spirv_cross/src/bindings.rs
- spirv_cross/src/glsl.rs
- spirv_cross/src/wrapper.cpp
- spirv_cross/src/wrapper.hpp
The GL compiler requires `build_combined_image_samplers` to have been called prior to compilation when any samplers are present. This commit calls it automatically without any special handling at the moment.
> GL combined image/samplers

- spirv_cross/Cargo.toml
- spirv_cross/src/compiler.rs
- spirv_cross/src/msl.rs
- spirv_cross/src/spirv.rs
The `BTreeMap` is needed to be able to hash stuff based on compiler options.
> [msl] use BTreeMap for overrides, fix version numbers

- spirv_cross/src/msl.rs
- spirv_cross/tests/msl_tests.rs
Before publishing 0.11.0, replace `is_rasterization_disabled` with `is_rasterization_enabled` to be consistent with compiler options.
> Rename to `is_rasterization_enabled`

- examples/src/glsl/main.rs
- examples/src/hlsl/main.rs
- examples/src/msl/main.rs
- spirv_cross/Cargo.toml
- spirv_cross/build.rs
- spirv_cross/src/bindings.rs
- spirv_cross/src/compiler.rs
- spirv_cross/src/msl.rs
- spirv_cross/src/spirv.rs
- spirv_cross/src/wrapper.cpp
- spirv_cross/src/wrapper.hpp
- spirv_cross/tests/glsl_tests.rs
- spirv_cross/tests/hlsl_tests.rs
- spirv_cross/tests/msl_tests.rs
- spirv_cross/tests/spirv_tests.rs
- Update submodule to latest SPIRV-Cross commit
- Add types exposed through the updated bindings
- Add format option for MSL vertex attributes
> Update to latest SPIRV-Cross master

- spirv_cross/Cargo.toml
- spirv_cross/src/msl.rs
- spirv_cross/tests/msl_tests.rs
Includes #100 (to fix the failed test)
> Update SPIRV-Cross to expose argument buffer binding

- spirv_cross/build.rs
This PR works around an iOS simulator build issue where the `c++14` flag was not being set when targeting ios.
For some reason `cc` is detecting `c++` as the default compiler which is just a thin wrapper around apple clang.
https://github.com/alexcrichton/cc-rs/issues/418
> workaround ios build issues

- spirv_cross/src/lib.rs
When another crate disabled on wasm32 still activates
hlsl or msl feature
> Fix wasm32 build on windows and metal

- appveyor.yml
- spirv_cross/build.rs
> [WIP] Try to fix CI when exceptions are disabled

- spirv_cross/build.rs
See [try log](https://treeherder.mozilla.org/logviewer.html#/jobs?job_id=269699182&repo=try&lineNumber=18469):
> [task 2019-10-03T23:46:17.607Z] 23:46:17     INFO -  [spirv_cross 0.15.0] cargo:warning=src/vendor/SPIRV-Cross/spirv_common.hpp(1308,4): error: cannot use 'throw' with exceptions disabled
[task 2019-10-03T23:46:17.607Z] 23:46:17     INFO -  [spirv_cross 0.15.0] cargo:warning=                        SPIRV_CROSS_THROW("Overwriting a variant with new type.");
[task 2019-10-03T23:46:17.608Z] 23:46:17     INFO -  [spirv_cross 0.15.0] cargo:warning=                        ^
[task 2019-10-03T23:46:17.608Z] 23:46:17     INFO -  [spirv_cross 0.15.0] cargo:warning=src/vendor/SPIRV-Cross/spirv_cross_error_handling.hpp(60,30): note: expanded from macro 'SPIRV_CROSS_THROW'
[task …
> Disable exceptions

- spirv_cross/src/bindings_native.rs
- spirv_cross/src/bindings_wasm.rs
- spirv_cross/src/compiler.rs
- spirv_cross/src/spirv.rs
- spirv_cross/src/wrapper.cpp
- spirv_cross/src/wrapper.hpp
https://github.com/grovesNL/spirv_cross/issues/117
Follows get_entry_points() because it also returns a Vec<_>.  Has no error condition, does not fail.
> Add active_buffer_ranges()

- .travis.yml
- .travis/linux_wasm.sh
- spirv_cross/src/bindings_wasm_functions.rs
I definitely messed up my fork with rebases, but the commits are all the same.
I'm not sure why spirv_cross msl/hlsl aren't working, but it seems someone disabled them in #111, maybe with good reason. So I changed the wasm CI script to only run the glsl example for that target(is that the only dialect that will run via javascript?).
> Add wasm bindings for buffer_ranges_function

- examples/src/glsl/main.rs
- spirv_cross/src/bindings_native.rs
- spirv_cross/src/bindings_wasm.rs
- spirv_cross/src/glsl.rs
- spirv_cross/src/wrapper.cpp
- spirv_cross/src/wrapper.hpp
- spirv_cross/tests/glsl_tests.rs
I just added the GLSL option to remove the version 420 extension in GLSL 410
i'm not comfortable enough with spirv-cross to add other options
I post this as a draft pull request because the ast_renames_interface_variables test doesn't succeed.
`assertion failed: (left == right)`
left: https://pastebin.com/kATJFEST
right: https://pastebin.com/SDuEKS5q
I have no idea why the precision lines gets added. i'm not that used to GLSL, even less to SPIRV-Cross and even less to the codebase of this rust binding. I hope you have an idea why
EDIT: activating the no_420_pack_extension option seems to enable ES for some reason
EDIT: i messed up some option orders. it now is fixed and ready for review
> Expose 420pack-extension GLSL option

- spirv_cross/Cargo.toml
This reduces build time on my machine from 60.1 seconds to 25.4 seconds.
This in turn reduces the build time on my project from 104 seconds to 68 seconds.
> Build in parallel

- examples/src/glsl/main.rs
- spirv_cross/src/bindings_native.rs
- spirv_cross/src/bindings_wasm.rs
- spirv_cross/src/bindings_wasm_functions.rs
- spirv_cross/src/glsl.rs
- spirv_cross/src/wrapper.cpp
- spirv_cross/src/wrapper.hpp
- spirv_cross/tests/glsl_tests.rs
- wasm/src/main.rs
Hi! I noticed that spirv_cross is missing some of the GLSL compiler options in the C++ header. Is this something spirv_cross is interested in?
Some design decisions to note (and nitpick!):
- Add missing fields to `CompilerGLSL::Options`
- `CompilerGLSL::Options::Precision` is marshalled through `wrapper.{cpp,hpp}` as a `uint8_t`
- This is a breaking change, as it adds fields to a `pub` struct.
- I think there's a pattern that can avoid this in the future, involving an unused private field which forces users to do the `..Default::default()`.
- Adds wrapper functions for the `CompilerGLSL` functions: `add_header_line` and `flatten_buffer_block`
- I did not add all the missing functions, just the ones I need.
- I ran `bindings_generator` on a Windows machine, which changed all the enum …
> Add missing GLSL compiler option fields/methods

- spirv_cross/src/lib.rs
With respect to https://github.com/grovesNL/spirv_cross/issues/49, I think that keeping an error type is the most flexible way to handle errors. This pull request implements Error (and by requirement, Display), to make integrating with other error types easier.
> implement std::error::Error for ErrorCode

- spirv_cross/Cargo.toml
Technically there are breaking changes in this patch release due to #160, however in practice it seems unlikely that it will cause problems for downstream crates. We'd prefer to release this as a patch release to avoid some dependency churn downstream (especially across gfx/wgpu/wgpu-rs).
If this does turn out to cause problems for other crates downstream, we can always yank this release and bump the minor version instead.
> Release 0.22.2

- spirv_cross/src/glsl.rs
- spirv_cross/src/hlsl.rs
- spirv_cross/src/msl.rs
Fixes #163
Also added non-exhaustive to versions, which will allow us to avoid breaking changes when we add more variants in the future.
> Add MSL 2.3 and make versions non-exhaustive

- spirv_cross/src/bindings_native.rs
- spirv_cross/src/bindings_wasm.rs
- spirv_cross/src/msl.rs
- spirv_cross/src/wrapper.cpp
- spirv_cross/src/wrapper.hpp
This option disables stripping unused fields from argument buffers. This ensures that argument buffers for vertex and fragment functions are identical, allowing the same argument encoder to be used for both. (See https://developer.apple.com/forums/thread/674406)
The binding generation didn't work for me locally (missing clang possibly). However this builds and has the intended effect.
> Add force_active_argument_buffer_resources to MSL compiler options

- spirv_cross/src/glsl.rs
Found from https://github.com/gfx-rs/wgpu-rs/issues/723
SPIRV-Cross builds combined image-samplers from entry point, so when it changes they must be rebuild.
> reset combined_image_samplers_build flag when entry_point changes
